# Generated by Django 3.2.9 on 2021-11-24 18:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211125_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compose',
            name='date',
        ),
        migrations.AddField(
            model_name='compose',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compose',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='compose',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='compose',
            name='slug',
            field=models.SlugField(max_length=1000, unique_for_date='publish'),
        ),
    ]
