# Generated by Django 3.2.9 on 2021-11-24 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211125_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compose',
            name='slug',
        ),
    ]
