# Generated by Django 3.2.9 on 2021-11-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='compose',
            name='slug',
            field=models.SlugField(default='', max_length=1000, unique_for_date='publish'),
        ),
        migrations.AlterField(
            model_name='compose',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
